version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: lockfile-only

  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
