name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run backend:test
      - name: Coveralls backend
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: "/packages/backend/coverage/lcov.info"
          base-path: "/packages/backend"
          flag-name: backend-${{ matrix.node-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run frontend:test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: "/packages/frontend/coverage/lcov.info"
          base-path: "/packages/frontend"
          flag-name: frontend-${{ matrix.node-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
